[build]
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."errand-routes"]
  timeout = 26

[functions."user-routes"]
  timeout = 26

[functions."other-function"]
  timeout = 26

  [functions."test-db-connection"]
  timeout = 26